<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\Survivors\**" />
    <Compile Remove="SkillStates\Regigigas\Misc\**" />
    <EmbeddedResource Remove="Modules\Survivors\**" />
    <EmbeddedResource Remove="SkillStates\Regigigas\Misc\**" />
    <None Remove="Modules\Survivors\**" />
    <None Remove="SkillStates\Regigigas\Misc\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="regigigas" />
    <None Remove="regigigas2" />
    <None Remove="RegigigasBank.bnk" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BepInEx.Core" Version="5.4.21" />
		<PackageReference Include="Moffein-Risky_Artifacts" Version="2.5.3" />
		<PackageReference Include="R2API.ContentManagement" Version="1.0.11" />
		<PackageReference Include="R2API.Core" Version="5.3.0" />
		<PackageReference Include="R2API.DamageType" Version="1.1.7" />
		<PackageReference Include="R2API.Director" Version="3.1.0" />
		<PackageReference Include="R2API.Items" Version="1.0.8" />
		<PackageReference Include="R2API.Language" Version="1.1.0" />
		<PackageReference Include="R2API.Networking" Version="1.0.4" />
		<PackageReference Include="R2API.Prefab" Version="1.1.1" />
		<PackageReference Include="R2API.RecalculateStats" Version="1.6.6" />
		<PackageReference Include="R2API.Skins" Version="1.4.7" />
		<PackageReference Include="R2API.Sound" Version="1.0.3" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.1-r.0" />
		<PackageReference Include="RoR2BepInExPack" Version="1.43.0" />
		<PackageReference Include="Rune580-Risk_Of_Options" Version="2.8.6" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.12.9">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="score-MiscFixes" Version="1.5.9" />
	</ItemGroup>

  <ItemGroup>
    <Reference Include="Decalicious">
      <HintPath>libs\Decalicious.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\..\Hunk\HunkProject\libs\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Modules\Components\SlowStartController.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call postbuild.bat $(TargetDir) $(AssemblyName)" />
  </Target>
  
</Project>
